### ISSUE TITLE
How do I see information about clients that are listening?

### ISSUE THREAD

**Issue by johnjelinek** [fanout/pushpin#47222]
Can I subscribe to get stats about pushpin? Is there a zmq channel or something?

**Comment by jkarneges** [comment]
Have a look at #47220.

**Comment by johnjelinek** [comment]
I'm running `python monitorstats.py ipc:///tmp/pushpin-stats` and `python monitorsubs.py` and then curl to one of my SSE streams, but I don't see any output. What am I doing wrong?

**Comment by jkarneges** [comment]
Are you running pushpin as root? Could be a permissions issue on the ipc files. If so, try doing "sudo chmod 777 /tmp/pushpin-stats" after pushpin is running and see if that helps.

**Comment by johnjelinek** [comment]
that was it, thanks @jkarneges!

**Comment by jkarneges** [comment]
I just added a new config option to make this easier:

    [handler]
    # ipc permissions (octal)
    ipc_file_mode=777

**Comment by johnjelinek** [comment]
Excellent!
