### ISSUE TITLE
Create /var/run/pushpin directory

### ISSUE THREAD

**Issue by chris-martin** [fanout/pushpin#47221]
I installed pushpin using apt-get, and got this when I tried to run it:

```
Traceback (most recent call last):
  File "/usr/bin/pushpin", line 56, in <module>
    runner.run(exedir, config_file, verbose)
  File "/usr/lib/pushpin/runner/runner.py", line 58, in run
    m2sqlpath = services.write_mongrel2_config(configdir, os.path.join(configdir, "mongrel2.conf.template"), rundir, logdir, http_port, https_ports, m2sh_bin)
  File "/usr/lib/pushpin/runner/services.py", line 34, in write_mongrel2_config
    compile_template(configpath, genconfigpath, vars)
  File "/usr/lib/pushpin/runner/services.py", line 11, in compile_template
    f = open(outfilename, "w")
IOError: [Errno 2] No such file or directory: '/var/run/pushpin/mongrel2.conf'
```

Workaround: Create `/var/run/pushpin` manually.

**Comment by jannic** [comment]
On a normal Debian (and probably Ubuntu, as well - please correct me if I'm wrong), /var/run is a ramdisk (tmpfs). Therefore, one can't simply create /var/run/pushpin at installation time: One needs to recreate it after every reboot. This is solved by the init script by testing if /var/run/pushpin exists, and creating it if necessary.
I guess you are not using the init script. That's fine, but in that case, you need to create /var/run/pushpin yourself, or change the configuration to point to another, existing directory.

**Comment by jkarneges** [comment]
Pushpin now attempts to create the needed directories on startup. So, if you run it as root after installation, it should be able to make the directories. Also it now defaults to /var/run instead of /var/local/run.

Of course creating the dirs in the init script has the advantage that pushpin can then be run as non-root.

**Comment by chris-martin** [comment]
Thanks!

To clarify, I was trying to run it in a docker container.
