### ISSUE TITLE
proxy ./configure doesn't generate right lib path for QtCrypto

### ISSUE THREAD

**Issue by fevin86** [fanout/pushpin#47224]
Installed qca with homebrew. The correct path for QtCrypto should be /usr/local/Cellar/qca/2.0.3/lib/qca.framework/Versions/2/Headers/QtCrypto, but is written to be /usr/local/Cellar/qca/2.0.3/include/QtCrypto

**Comment by jkarneges** [comment]
Try upgrading qca. When I installed it from brew, I got version 2.1.0, and proxy's ./configure set the correct includepath in ``conf.pri``:

    INCLUDEPATH += /usr/local/Cellar/qca/2.1.0/lib/qca.framework/Headers [...]

**Comment by jkarneges** [comment]
Hey @fevin86, did upgrading qca fix this for you?

**Comment by jkarneges** [comment]
I just going to assume this was an issue in the older package. Please reopen the issue if this is not the case.
