### ISSUE TITLE
Examples of using stats via HTTP

### ISSUE THREAD

**Issue by james-andrewsmith** [fanout/pushpin#47220]
Hi @jkarneges,

Having a lot of fun playing with pushpin! Love the approach, I never realised how much time I was spending solving "socket" problems vs application problems before, and it's so nice to have it handled so simply. 

I saw somewhere that for scaling multiple instances one could use a stat service for querying subscriptions.

Is this an HTTP endpoint or ZMQ? If so what are it's specs? How can one get at this data?

Many Thanks!

**Comment by jkarneges** [comment]
Hi James,

The stats socket is a ZMQ PUB socket living at ipc:///tmp/pushpin-stats (you can change this in pushpin.conf, [handler] section, stats_spec field).

The format of the messages are "{stat type} T{tnetstring message}". In the tools directory there are a couple of programs for trying this out. Use monitorstats.py to just dump all message types, and use monitorsubs.py to see how subscription tracking can work.

**Comment by jkarneges** [comment]
I've just now added optional input via a ZMQ SUB socket. This is a little easier to use because the ZMQ library itself handles the subscription tracking. Set the spec in pushpin.conf, [handler] section, push_in_sub_spec field.

Then in your app you can just do:

```python
sock = ctx.socket(zmq.PUB)
sock.connect(...)

# make sure we're connected
time.sleep(0.5)

sock.send_multipart([channel, {item}])
```

Messages are multipart, where the first part is the channel string, and the second part is the tnetstring item to publish. If there are no subscriptions, then the ZMQ library simply drops the message without anything going over the network.

**Comment by james-andrewsmith** [comment]
@jkarneges Thank you for the quick response.

I just want to confirm I understand this awesome awesomeness, before I start raining praise and thanks for simplifying my life. 

1. I can have my app use a ZMQ library to connect to the configured ZMQ socket (I'm in C# land so NetMQ)
2. My app will publish to this socket (eg: tcp://pushpin-server-ip-or-hostname:12345) which matches the push_in_sub_spec field.
3. The message format is multipart which I believe in NetMQ is called frames, is basically Frame 1 = Channel, Frame 2 = {Content To Publish}
4. Due to the "magic" in ZMQ, when I publish messages to a channel which has no subscribers in pushpin it isn't even wasting network bandwidth.
5. I can therefore use ZMQ to publish to all the pushpin servers without losing sleep about inefficiencies in the environment.

**Comment by jkarneges** [comment]
Yes. :) I even confirmed with tcpdump. Let me know how it goes.

**Comment by james-andrewsmith** [comment]
@jkarneges - This works so well!!! Thank you for adding it.

Unfortunately I haven't found a good typed netstring library for .NET - but as I don't use the format widely I can hand write a serializer for this message type.

Kudos again for coming up with this approach - the whole architecture has a great "feel"
