### ISSUE TITLE
Using Python sortedcontainers vs blist

### ISSUE THREAD

**Issue by grantjenks** [fanout/pushpin#47229]
First, thanks for a great package. I'm exploring real-time Django solutions and am currently evaluating this.

I noticed that the project is using the Python blist module, in particular the sorteddict data type is used for expiring subs by time. As the author of the sortedcontainers module, I wondered why. SortedContainers is a pure-Python implementation of SortedList, SortedDict, and SortedSet data types. For your use pattern of getting, setting, deleting, and iterating sortedcontainers.SortedDict looks faster than blist.sorteddict. Take a look at the benchmarks at http://www.grantjenks.com/docs/sortedcontainers/performance.html#id2

But then I noticed that your typical install instructions are a list of Debian packages. And sortedcontainers doesn't have a Debian package (though someone recently requested that (https://github.com/grantjenks/sorted_containers/issues/29) so I wanted to ask:

1. How did you choose blist?
2. Is the lack of a Debian package for sortedcontainers a deal breaker?
3. Would you accept a pull request that changed the dependency and made the code a bit more idiomatic? In particular, I'd be really curious to test any benchmark that might be affected by such a change.

Thanks for reading.

**Comment by jkarneges** [comment]
You guessed right: the reasoning was Debian package availability. Lack of a package for sortedcontainers is basically a dealbreaker since we wouldn't be able to make a proper Debian package for Pushpin itself.

We can throw @jannic at this problem if you'd like the assistance. He handles our Debian packages.

**Comment by jannic** [comment]
As Grant already noticed, there is an ITP by @sandrotosi for packaging sortedcontainers, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790504 for details. Looking at the packages Sandro maintains, he seems to have much more experience packaging python packages than I do. Still, Sandro, if you need any assistance, feel free to contact me!

**Comment by sandrotosi** [comment]
Thanks @jannic but I guess I'm good here, we are just waiting for the package to be approved into our repository (it is needed only the first time a package 'appears' for inclusion into Debian)

**Comment by sandrotosi** [comment]
sortedcontainers has just been accepted into Debian (unstable)

**Comment by grantjenks** [comment]
Thanks @sandrotosi !!!

@jkarneges Does this satisfy your need for a Debian package? It looks to be available in sid (unstable).

**Comment by jkarneges** [comment]
Yes. I think we should make the code work both ways for a little while though, at least until the package gets picked up by Ubuntu 15.10. Can you make a PR that opportunistically uses sortedcontainers?

**Comment by grantjenks** [comment]
Pull request merged to develop branch: #47231 

Let me know when/if you want me to update the wiki pages.

**Comment by jkarneges** [comment]
Sure, you can update the wiki. Just be sure to note it as optional for now. After October we can change the default apt-get instructions.

**Comment by grantjenks** [comment]
Thanks. Done.

**Comment by jkarneges** [comment]
Thanks, looks good. I'll also update the Homebrew package to use sortedcontainers when I release a new version later this week.

The Debian packages will be updated when it makes sense to. We are considering setting up our own apt repo for backports, so this could happen sooner than later.
