### ISSUE TITLE
Connection reset when filesize is big

### ISSUE THREAD

**Issue by eterna2** [fanout/pushpin#47238]
I am using hapi as api server. And testing via request.

test_request.js
```
fs.createReadStream('./workbooks/tmp/somefile.csv')
  .pipe(
    request({
      method: 'POST',
      url: 'https://some.domain.com/some_route',
      qs: {
        params: {
          param_a: 'some_param'
        },
        email: 'some@email.com',
        prj: 'someprj'
      },
      agentOptions: {
        ca: fs.readFileSync('./ssl/cert.pem')
      }      
    },function(err,response,body){
      if (err) console.log(err);
      console.log(body);
    })
  )
  .on('error', function(err){
    console.log(err.stack);
  });
```

hapi_route.js
```
module.exports = {
  method  : "POST",
  path    : "/some_route",
  config: { 
    auth: false,
    payload: {
      maxBytes: 100*1024*1024,
      output: 'stream'
      parse: false
    }
  },
  handler : handleRoute
};
```

I get this error
```
Bad Request
Error: write ECONNRESET
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)

```

if I just send the content as a chunk

test_request.js
```
request({
      method: 'POST',
      url: 'https://some.domain.com/some_route',
      qs: {
        params: {
          param_a: 'some_param'
        },
        email: 'some@email.com',
        prj: 'someprj'
      },
      agentOptions: {
        ca: fs.readFileSync('./ssl/cert.pem')
      } ,
     body: fs.readFileSync('somefile.csv')
    },function(err,response,body){
      if (err) console.log(err);
      console.log(body);
    })
```

hapi_route.js
```
module.exports = {
  method  : "POST",
  path    : "/some_route",
  config: { 
    auth: false,
    payload: {
      maxBytes: 100*1024*1024,
      parse: false
    }
  },
  handler : handleRoute
};
```

I get this error
```
{ [Error: socket hang up] code: 'ECONNRESET' }
```

however, if I try with a smaller file, everything is working fine. I can't seem to find any configuration to control the max payload size in pushpin? I assume there should be some equivalent to nginx's upload_max_filesize??

**Comment by jkarneges** [comment]
There used to be some bugs with large uploads, but I believe they were fixed. What version of Pushpin, Zurl, and Mongrel2 are you using?

**Comment by eterna2** [comment]
I am using  johnjelinek's docker image.

https://github.com/johnjelinek/pushpin-docker

pushpin 1.6.0
mongrel2-core 1.9.2-1
zurl 1.4.9-1

**Comment by jkarneges** [comment]
Can you try Mongrel2 1.10? I believe it shouldn't be too hard to modify the Dockerfile to build that from source as well.

**Comment by jkarneges** [comment]
Maybe @johnjelinek can offer a suggestion for modification.

**Comment by johnjelinek** [comment]
Is there a fix in the updates versions of mongrel2/zurl that would effect streaming larger files?

**Comment by jkarneges** [comment]
I'll do some tests with older versions and report back.

**Comment by jkarneges** [comment]
Tested:
* Pushpin 1.6.0 + Mongrel2 1.9.2 + Zurl 1.4.9 fails with large uploads
* Pushpin 1.6.0 + Mongrel2 1.9.2 + Zurl 1.4.10 works fine

So I think only the Zurl update is needed.

**Comment by jkarneges** [comment]
And yes I should clarify, Zurl indeed had a fix for large uploads. In fact that's the only change between 1.4.9 and 1.4.10.

Mongrel2 had a bunch of I/O updates. Nothing specifically for large uploads, but I wondered if they were necessary. Seems not.

**Comment by johnjelinek** [comment]
ok, I'll push an update to the dockerfile to match the latest ZURL version

**Comment by johnjelinek** [comment]
hrmm ... I get an error when running pushpin, when I've built zurl manually (w/ libcurl4-gnutls-dev):
```
Traceback (most recent call last):
  File "./pushpin", line 60, in <module>
    runner.run(exedir, config_file, verbose)
  File "/pushpin/runner/runner.py", line 108, in run
    pid = p.add(s.name(), s.getargs(), s.getlogfile(), s.accept_sighup())
  File "/pushpin/runner/processmanager.py", line 81, in add
    p.start(args, logfile, accept_sighup)
  File "/pushpin/runner/processmanager.py", line 26, in start
    self.proc = subprocess.Popen(args, stdout=fp, stderr=subprocess.STDOUT, preexec_fn=self._preexec_fn)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by johnjelinek** [comment]
I see if I install zurl from apt-get, I see it installs some systemd init stuff. Maybe I need to make something comparable to start the service before running pushpin

**Comment by johnjelinek** [comment]
herp* derp* forgot `make install`

**Comment by johnjelinek** [comment]
ok, new image is building on dockerhub now.

**Comment by johnjelinek** [comment]
@eterna2: ok, pull latest / 1.6.0 -- they are both updated.

**Comment by eterna2** [comment]
Sorry for the late reply - different timezone. 

I have pulled the new version, and it works! Thanks!!
