### ISSUE TITLE
Docker-compose with Pushpin

### ISSUE THREAD

**Issue by eterna2** [fanout/pushpin#47237]
Was trying out the docker image from johnjelinek, but seems to have problem getting it to work with Docker compose due to the need of a tty by mongrel2.

I got the following error:
```
(errno: Inappropriate ioctl for device) getlogin failed and no LOGNAME env variable, how'd you do that?
```

I am not too familiar with mongrel2, any ideas what I need to tweak so that an automated script can start pushpin without tty?

**Comment by jkarneges** [comment]
It looks like this occurs in `m2sh`, which Pushpin uses to compile the mongrel2 config file. It wants to know the acting user, for logging purposes. Try setting `LOGNAME=nobody` or such.

**Comment by eterna2** [comment]
Great it works now!
