### ISSUE TITLE
Feature Request: Replace Path

### ISSUE THREAD

**Issue by johnjelinek** [fanout/pushpin#47233]
I want to proxy routes from `http://localhost:7999/something/*` to `http://backend:8080/something_else/*`, replacing `something` with `something_else`.

**Comment by jkarneges** [comment]
How about a ``replace_beg`` field where you can set a replacement for what is specified by ``path_beg``? E.g.:

    *,path_beg=/something/,replace_beg=/something_else/ backend:8080

It could also be used as a more intuitive replacement for ``path_rem``.

    *,path_beg=/v2,replace_beg= backend:8080

**Comment by johnjelinek** [comment]
I think that looks good



—

**Comment by jkarneges** [comment]
Seems easy enough so I took care of it now: 296ce97de4a50a1a754c4928d58d3611ebfa31ad

**Comment by johnjelinek** [comment]
:+1: thanks! I'll update the Dockerfile once this gets merged into `master` and there's a version bump.

**Comment by johnjelinek** [comment]
I'm testing out `replace_beg`, but I keep getting `No route for host: myhost.example.com`. I'm wanting http://myhost.example.com/abc.txt to map to https://myrealhost.example.com/v0/abc.txt.

**Comment by johnjelinek** [comment]
the requests work if I include the `v0` path prefix.

**Comment by jkarneges** [comment]
Ah, it seems you can't set `path_beg` to an empty value or the route will never match. Is this what you're doing? If you have no beginning to match, just leave it off. This works for me:

```
myhost.example.com,replace_beg=/v0 myrealhost.example.com:80
```

**Comment by johnjelinek** [comment]
:+1:
