### ISSUE TITLE
route review

### ISSUE THREAD

**Issue by johnjelinek** [fanout/pushpin#47232]
routes:
```
*,path_beg=/test localhost:8080,path_beg=/test
*,ssl=no,path_beg=/v2 acceptor:8080,path_beg=/v2,path_rem=3
```

In my scenario, I would like traffic to `localhost:7999/test` to go to `localhost:8080/test` (where I am not hosting somewhere, so I expect an error) and I get the expected result until I hit a route that matches the second scenario. Then the second route responds to requests mentioned in the first route.

In the second route, I would like `localhost:7999/v2/abc` to go to `acceptor:8080/abc` but it is proxying the whole path `acceptor:8080/v2/abc`. Also, when I make changes to the routes, it's not always reflecting the changes unless I restart pushpin -- I don't think that's expected, right?

**Comment by johnjelinek** [comment]
As an aside, I have some public URLs I'd like to reverse proxy to as well and I can ping/curl those servers, but I can't seem to have pushpin proxy to those. Example route:
```
*,path_beg=/api api.example.com:443,ssl,insecure,path_beg=/?apiKey=123
```

**Comment by jkarneges** [comment]
The ``path_beg`` and ``path_rem`` params only work on the route condition, not the target. If you want to hack off the /v2 when proxying, do it like this:

    *,ssl=no,path_beg=/v2,path_rem=3 acceptor:8080

I'm not sure what you're trying to do in your second comment, but it's not possible to match on query string nor have a query parameter added when proxying.

Regarding route file change detection, I have run into random occasions when the the filesystem detection doesn't work. You can send SIGHUP to be certain.

**Comment by johnjelinek** [comment]
thx for the route help, regarding my second comment -- I can't set my target to an external DNS name (ie: a public API that I want to reverse proxy and optionally hard-code an API key in the target path).

**Comment by jkarneges** [comment]
Hmm, targeting a public domain name should work. Try running pushpin with the ``--verbose`` option and have a look at zurl.log when making a request to see what's going on.

**Comment by johnjelinek** [comment]
strange, it's working now. Thanks for your help!

**Comment by johnjelinek** [comment]
@jkarneges: is there a replace feature? ie: `source/v2 -> target/v3`

**Comment by jkarneges** [comment]
There isn't, but you can file that separately as a feature request.
