### ISSUE TITLE
publish to close websockets

### ISSUE THREAD

**Issue by jkarneges** [fanout/pushpin#47624]
Pushpin's HTTP streaming mode enables the publisher to close connections. We should support something similar with WebSockets, e.g.:

```
"ws-message": {
  "action": "close"
}
```

**Comment by fomojola** [comment]
Ah, just found this after a fruitless 2 hours of trying to figure out how to close a websocket when using the  websocket-over-HTTP mode. Is there currently really no way to signal to the proxy that it should close a connection from the server? I'll accept ANY alternate channel, but this is a pretty significant deficiency in the protocol: right now this says that the only time the server can explicitly close a websocket is on the initial connection, and that once that initial connection is closed there is no way to send any other Websocket event besides TEXT and BINARY.

**Comment by fomojola** [comment]
Looking at the source, it appears that https://github.com/fanout/pushpin/blob/master/src/handler/engine.cpp#L1662 is the publish processor. It currently only generates items of type WsControlPacket::Item::Send;.

Would it be possible to simply support additional content types? Edit https://github.com/fanout/pushpin/blob/master/src/handler/publishformat.cpp#L268 so it searches for an "action" field and sets a flag that can be used to control the WsControlPacket::Item type field?

**Comment by jkarneges** [comment]
Servers usually don't need to spontaneously close connections, which is why this feature hasn't been implemented yet. What's your use case?

One thing you could do is respond with the `Keep-Alive-Interval` header. The spec doesn't say much about this yet, but you set it to a value in seconds, and if that much time passes without contact with the origin server, then Pushpin will make an HTTP request to the server with no events (empty body). This would give the server an opportunity to respond with events every once in awhile as opposed to potentially never.

I agree it ought to be possible to publish any kind of frame. We should use `action` to indicate send or close, with send being the default. I suppose we should also be able to specify a close code.

Here's a proposal:

Closing:

```
"ws-message": {
  "action": "close",
  "code": 1000     // optional
}
```

Arbitrary frame by name:

```
"ws-message": {
  "frame": "ping"
}
```

This could be used for just the types in the RFC.

Arbitrary frame by opcode:

```
"ws-message": {
  "frame": 9,
  "content": "foo"
}
```

This could be used to specify any kind of frame. In practice I'm not sure when this would get used but it could be good to have.

Currently, `content` implies a text frame and `content-bin` implies a binary frame. However, if `frame` is specified then either `content` or `content-bin` could be used to specify the data of the frame with no effect on the frame type.

Frame types 0 (continuation) and 8 (close) wouldn't be allowed with the send action.

**Comment by fomojola** [comment]
Justin,
  thanks for the update: the outlined proposal looks great. 

The use case for me is actually load shedding/balancing: I'm "streaming" data to a ChromeCast device via websocket and for load shedding/balancing I just want to initiate the close from the server: the client implementation is already written up to simply relaunch the connection. Now I can simply mark the server as disabled via Haproxy's admin socket (so it accepts no new connections), cleanly close the connections on the server and then terminate the VM. My autoscaling group will bring up another VM and add it to the list of available backends and then its back to work.

**Comment by jkarneges** [comment]
This is now implemented in the develop branch, except for the part about specifying arbitrary types by integer. Most of the codebase doesn't work directly with opcodes like that so it's a little more work to implement. We'll wait until someone actually needs it. The field for setting the message type is called `type` instead of `frame` (edited my earlier post to match).
