### ISSUE TITLE
Request body size bug

### ISSUE THREAD

**Issue by neorusa** [fanout/pushpin#47628]
When pushpin gets a request, it compares all request size (header and body) with MAX_HEADERS_SIZE. So, our requests size are limited with this value.

in src/handler/httpserver.cpp:
in void processIn():
	
Line 219: QByteArray buf = sock->readAll(); // Reads all request
Line 223: if(inBuf.size() + buf.size() > MAX_HEADERS_SIZE) // Comparses request size with headers max size value

**Comment by jkarneges** [comment]
Good catch. Fixed: 997d84143d8bd3992b04a22142e148c636ba67bb
