### ISSUE TITLE
Host header incorrect when port present

### ISSUE THREAD

**Issue by charliewolf** [fanout/pushpin#47632]
If you run pushpin on port 8000 and visit `localhost:8000`, it sends:
    `Host: localhost`

It should send:
   `Host: localhost:8000`

This doesn't follow the [HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23) and can break redirects.

**Comment by jkarneges** [comment]
I agree that this is probably not correct behavior and indeed it will mess with redirects, so I think we can fix this.

Also, if someone really wants an altered Host header, we have the `as_host` and `host` parameters now.

**Comment by jkarneges** [comment]
This is now implemented in the develop branch. Will look at doing a release later this week. Note that it also requires using the develop branch of zurl.
