### ISSUE TITLE
SockJS support

### ISSUE THREAD

**Issue by chancezeus** [fanout/pushpin#47633]
In a project I need to build a chat server and I wanted to use Pushpin as a proxy between a Laravel (PHP) app and sockjs on the client.
At the moment I can connect the client successfully and receive messages broadcasted an a channel. But when I try to send a message it does not seem to call the backend (backend only get's called on initial connection).

I am using the "fanout/laravel-grip" package and the following code (for now it should be an echo server, if that works I can start building the actual functionality)...

```
        \Log::info('(' . time() . ') chat');

        \LaravelGrip\verify_is_websocket();

        /** @var WebSocketContext $context */
        $context = \LaravelGrip\get_wscontext();

        if ($context->is_opening()) {
            $context->accept();
            $context->subscribe('test');
        }

        while($context->can_recv()) {
            $message = $context->recv();
            \Log::info('Received message', ['message' => $message]);

            if (is_null($message)) {
                $context->close();
                break;
            }

            $context->send($message);

            \LaravelGrip\publish('test', new WebSocketMessageFormat($message));
        }

        return null;
```

If I look into the laravel logfile I can see the log message only being called on the initial client connection not when the client sends a message.

The route is
```
*,debug,sockjs=/sockjs,sockjs_as_path=/chat localhost:80,over_http
```

When connecting a regular websocket to /chat it works without a problem. Does sockjs require any special handling (compared to regular websockets), since I assumed that sockjs emulated websockets behave like regular ones (ie. when a message is received a post request is send to the backend, after which the backend handles the message and sends a response/publishes a message on a channel/etc)...

**Comment by jkarneges** [comment]
It seems SockJS was somewhat broken in the most recent release. I've just now put a fix in the develop branch. Please test if you can.

Also your assumption is correct, that SockJS-emulated websockets look the same as regular websockets to your backend.

**Comment by chancezeus** [comment]
Just tried it and the fix seems to work, any chance to see this integrated into a debian/ubuntu package? Or maybe update the repository to include source packages so I can patch it myself?

**Comment by jkarneges** [comment]
Thanks for testing. We'll get a new package out this week.
