### ISSUE TITLE
Release notifications

### ISSUE THREAD

**Issue by charliewolf** [fanout/pushpin#47643]
I maintain Arch Linux's AUR packages for `pushpin` and `zurl`. It would be great if there was a way to know when new versions were released (a mailing list or some other similar method) so I could update said packages in a timely fashion.

**Comment by jkarneges** [comment]
Hi @charliewolf, there is indeed a mailing list where announcements are posted: https://lists.fanout.io/mailman/listinfo/fanout-users

**Comment by charliewolf** [comment]
Aha. That does the trick. Thanks.
