### ISSUE TITLE
SUB to stats socket not working

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [fanout/pushpin#47642]
The demo Python program (pasted below) that connects to the stats socket and prints the decoded messages is stuck at the `sock.recv()` and does not print anything, although I can successfully have pushpin play along with clients and origin server. The permissions on the socket look good (`srwxr-xr-x 1 pushpin zurl `). Am I missing anything? Thanks!

```
import sys
import tnetstring
import zmq

ctx = zmq.Context()
sock = ctx.socket(zmq.SUB)
sock.connect('ipc://var/run/pushpin/pushpin-stats')
sock.setsockopt(zmq.SUBSCRIBE, '')

while True:
    m_raw = sock.recv()
    mtype, mdata = m_raw.split(' ', 1)
    if mdata[0] != 'T':
        print 'unsupported format'
        continue
    m = tnetstring.loads(mdata[1:])
    print '%s %s' % (mtype, m)
```

**Comment by jkarneges** [comment]
I believe zmq ipc requires writability regardless of which direction the data is logically flowing. Try `777` perms and see if that helps.

**Comment by alessandrousseglioviretta** [comment]
Done, the perms are now `srwxrwxrwx`, but it still doesn't work. I also restarted pushpin, just in case, to no avail.

**Comment by jkarneges** [comment]
The filename should probably be `ipc:///var/run/pushpin/pushpin-stats` (note the triple slash), otherwise it would be a relative path from where you run this code.

**Comment by alessandrousseglioviretta** [comment]
Good point: it might be wise to add a note or change the code at http://pushpin.org/docs/advanced/#stats-socket. Alas, it still doesn't work.

**Comment by jkarneges** [comment]
Thanks for pointing out that typo. Fixed.

The only other thing I can think of is a ZeroMQ versioning issue. What OS are you running? Did you install the python `zmq` package from the OS or pip?

**Comment by alessandrousseglioviretta** [comment]
I'm on Ubuntu 14.04 3.13.0-106-generic, Python 2.7.6 [GCC 4.8.2] in virtualenv-13.1.2. Uhm... could virtualenv be the issue?

**Comment by jkarneges** [comment]
When you install `zmq` via pip, it'll build its own copy of zmq if it can't find the dev files of your system zmq. This can lead to mismatching versions used between your programs in the virtualenv and programs on the system (such as Pushpin, assuming you're using the Ubuntu package). Try `sudo apt-get install libzmq3-dev` so the dev files exist on the system, and then pip uninstall/install zmq within the virtualenv again.

**Comment by alessandrousseglioviretta** [comment]
`libzmq3-dev` was already installed, I reinstalled `pyzmq` (version 16.0.2) but I still get nothing out of the socket.

**Comment by jkarneges** [comment]
Can you install the `python-zmq` Ubuntu package and run the code without the virtualenv to see if that works?

**Comment by jkarneges** [comment]
Also note if you restart Pushpin then the permissions on the pipe file may revert, so be sure to chmod again. Or set `ipc_file_mode` in pushpin.conf

**Comment by alessandrousseglioviretta** [comment]
The virtualenv-free install still did not work, but setting again the permissions did the trick! I re-tested it within the virtualenv and it's all working fine. As I installed `libzmq3-dev` long ago, the most likely issue was simply the triple-slash. Thank you!

**Comment by jkarneges** [comment]
Whew, glad we figured it out. :)
