### ISSUE TITLE
Pushpin retries the requests indefinitely if channel name changes between requests

### ISSUE THREAD

**Issue by j-manu** [fanout/pushpin#47646]
We have a unique use case in which each client gets a unique channel which is used to publish a message only once. This worked perfectly in 1.14. But in 1.15 for each new channel, the first request is always retried. So if the channel changes between requests, pushpin indefinitely retries the requests

Sample server code to reproduce the problem in ruby
```ruby
require 'sinatra'
require 'json'
require 'pp'
require 'securerandom'
get '/hold' do
  #pp request.env
  headers \
    'Grip-Hold' => 'response',
    'Grip-Channel' => SecureRandom.uuid,
    'Content-Type' => 'application/json'
  '{"resp": "timeout"}'
end
```

```
curl http://localhost:7999/hold
```

**Comment by jkarneges** [comment]
Interesting problem. The retry after first subscriber to a channel is intentional behavior, to reduce the chance of a missed message when publishers use subscription tracking.

What's your use case?

**Comment by j-manu** [comment]
We have an API endpoint to which clients can submit content to be transformed to PDF via HTTP POST request. The PDF generation is async but we didn't want the clients to deal with polling or webhooks. So we have api server -> pushpin -> client. For each client submission, we generate a unique channel and let pushpin hold the connection. Once the PDF generation is complete, we publish the response to the appropriate channel. So each channel gets only a single message (success or failed)

If pushpin can add a header to the retry request, we can solve this by ignoring the retry. Maybe prev-id?

**Comment by jkarneges** [comment]
Cool use case, and yes I think a header is the right approach. Stream mode recovery requests send `Grip-Last` containing last known channel IDs, and probably the same should be done with response mode retries. For every subscribed channel, there would be a request header:

```
Grip-Last: foochannel; last-id=bar
```

I'll consider this for the next release.

**Comment by jkarneges** [comment]
In the develop branch.

**Comment by j-manu** [comment]
Thank you!
