### ISSUE TITLE
Is it possible to query a pushpin instance to see if a given ID is still connected?

### ISSUE THREAD

**Issue by charliewolf** [fanout/pushpin#47648]
I see in the docs you mention connection checking with IDs like m2zhttp_45517:pushpin-m2-7999_1_0. Is it possible to query to see if a connection id returned in the `Connection-Id` header in a websocker-over-http call is still connected?

**Comment by jkarneges** [comment]
Yes it should work. In the case of WebSocket connections, the IDs exposed by the stats socket are the same as the `Connection-Id` header.

**Comment by jkarneges** [comment]
Considering this answered. Can always re-open if otherwise.
