### ISSUE TITLE
Checking Pushpin with PVS-Studio static analyzer

### ISSUE THREAD

**Issue by khandeliants** [fanout/pushpin#47647]
Hello,
I have found some weaknesses and bugs using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

Analyzer warnings:

* [V509](https://www.viva64.com/en/w/V509/) The 'new' operator should be located inside the try..catch block, as it could potentially generate an exception. Raising exception inside the destructor is illegal. [src/proxy/websocketoverhttp.cpp 929](https://github.com/fanout/pushpin/blob/master/src/proxy/websocketoverhttp.cpp#L929)

* [V595](https://www.viva64.com/en/w/V595/) ([CWE-476](https://cwe.mitre.org/data/definitions/476.html)) V595 The 'inRequest' pointer was utilized before it was verified against nullptr. Check lines: [452](https://github.com/fanout/pushpin/blob/master/src/proxy/proxysession.cpp#L452), [475](https://github.com/fanout/pushpin/blob/master/src/proxy/proxysession.cpp#L475). [src/proxy/proxysession.cpp 452](https://github.com/fanout/pushpin/blob/master/src/proxy/proxysession.cpp#L452)

In addition, I suggest having a look at the emails, sent from @pvs-studio.com.

Best regards,
Phillip Khandeliants

**Comment by jkarneges** [comment]
First issue: We don't explicitly use exceptions anywhere, and allocation failures should cause the program to abort anyway, so for now we don't consider this to be a real problem.

Second issue: Fixed.
