### ISSUE TITLE
Django WebSocket Browser: connection refused

### ISSUE THREAD

**Issue by mbhassan** [fanout/pushpin#47649]
Got a django endpoint which is working well with an http curl from cli, but connection gets refused when attempting to create a websocket object in browser.

JS Console in Chrome:
var ws = new WebSocket('ws://localhost:7999/dashboard/stream/');

WebSocket connection to 'ws://localhost:7999/dashboard/stream/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

enabled the over_http with no luck.

Django server registers no incoming requests when attempting websocket conn from browser.

**Comment by jkarneges** [comment]
What if you try outside of the browser, for example with wscat?

**Comment by mbhassan** [comment]
with wscat, django is seeing incoming requests.

**Comment by jkarneges** [comment]
Hmm, might be a browser security issue? Try using a CORS middleware (placed before `django_grip.GripMiddleware`, if you're using that), or turn on Pushpin's auto CORS support (`auto_cross_origin=true` in pushpin.conf, or `aco` route param).

**Comment by mbhassan** [comment]
cors support also turned on. issue still persists.

**Comment by jkarneges** [comment]
What Pushpin version? Anything in m2adapter.log?

**Comment by mbhassan** [comment]
1.10. only requests made using wscat & curl (http) visible in the log.

**Comment by jkarneges** [comment]
Maybe an IPv6 thing? Try ws://127.0.0.1:7999/dashboard/stream/

**Comment by mbhassan** [comment]
connection still refused. Can confirm that websocket works well using wscat. WS is working in the browser as django registers the request if port is changed to 8000 in ws browser object. Seems like pushpin isnt passing ws from within browser. Will upgrade to latest version and check

**Comment by mbhassan** [comment]
resolved. Forgot to forward port 7999 on vagrant.
