### ISSUE TITLE
Grip-Sig header is not regenerated for WS-Over-Http backend

### ISSUE THREAD

**Issue by acmcelwee** [fanout/pushpin#47657]
Discussion from gitter channel:
> Adam McElwee @acmcelwee 14:41
@jkarneges am I right in interpreting that the Grip-Sig headers aren't regenerated again for keep-alive requests to the backend?

> Adam McElwee @acmcelwee 15:24
I guess I should also ask if Grip-Sig is the best way for us to ensure the request to our backend is from the pushpin proxy.
via websockets over http as the protocol
Basically, we're seeing grip-sig validation fail, and when we dig in on all of them, the jwt expiry is the issue.
so, we're just trying to track down why those grip-sig header contents would be expired
keep-alive-interval is set to 20 seconds on the initial response

> Justin Karneges @jkarneges 15:54
@acmcelwee good catch. it seems they are not regenerated. I'd say that's a bug

> Adam McElwee @acmcelwee 15:54
Let me look at it and see if it's easy enough for me to submit a PR.
Otherwise, I'll open up an issue.

**Comment by jkarneges** [comment]
Done in the develop branch.
