### ISSUE TITLE
Handler Log Level

### ISSUE THREAD

**Issue by thebubbleindex** [fanout/pushpin#47658]
I would like to turn off logging. I have tried editing the pushpin.conf file field to: log_level=0 and also log_level=-1 but neither seem to have any effect on the handler.log file. I want to turn off logging because in some cases the handler log files are growing to gigabytes.

**Comment by jkarneges** [comment]
Log level control is quite primitive at the moment. It's either verbose (>=3) or normal (<=2) and doesn't affect Mongrel2 logs. Best thing to do is rotate log files. Then hopefully the info-level logging will be okay.

I do want to improve this though, so will leave this issue open.

**Comment by jkarneges** [comment]
Fixed in #47673
