### ISSUE TITLE
Installing PushPin on AWS 

### ISSUE THREAD

**Issue by pentyala** [fanout/pushpin#47655]
Hi! 
I am running my application on AWS elastic beanstalk and Can I know the steps needed to run Pushpin service on AWS?

**Comment by jkarneges** [comment]
Hi, I've installed Pushpin on EC2 manually and with Ansible, by simply using apt as described [https://pushpin.org/docs/install/](here). However I've never used beanstalk. I suggest asking about that in the [https://gitter.im/fanout/pushpin](chatroom) in case others know.
