### ISSUE TITLE
websocket over HTTP : Content-Length not overwritten

### ISSUE THREAD

**Issue by Gingonic** [fanout/pushpin#47663]
Hi,

I'm trying to get Pushpin (1.19.1-1~bionic1, on Ubuntu 18.1) behind an Envoy Proxy.  The proxy is setting "Content-Length=0" while proxying to Pushpin. Pushpin keeps this header and sends it to the backend  when translating the WS to HTTP while sending the "OPEN" command.
 So we end with following headers (taken from the logs):
`[ [ "Content-Length", "0" ], [ "Host", "XXXXXX" ], [ "Sec-Websocket-Key", "XXXXX" ], [ "Sec-Websocket-Version", "13" ], [ "Sec-WebSocket-Extensions", "grip" ], [ "Grip-Sig", "xxxxx" ], [ "Grip-Feature", "status, session, link:next, filter:skip-self, filter:skip-users, filter:require-sub, filter:build-id" ], [ "X-Forwarded-For", "10.244.0.1" ], [ "Accept", "application/websocket-events" ], [ "Connection-Id", "0ecd221b-dd5c-4384-a38f-887f7174f1a5" ], [ "Content-Type", "application/websocket-events" ], [ "Content-Length", "6" ] ]
`

As you can see the content-length is entered twice and I guess only the first one is sent to the backend (or the backend HTTP server only takes the first). Which has the effect that the backend HTTP server drops the content and the connection cannot be established.

As far as I can see the behavior on the proxy side is unusual and not completely in accordance with the specs, but I still think that Pushpin should handle this on the WS to HTTP transformer level.

Any though on how to by-pass the issue on the Pushpin level?

Cheers

**Comment by jkarneges** [comment]
Thanks for the report! I agree Pushpin should not forward this header. This issue is now fixed in version 1.20.1.
