### ISSUE TITLE
[Proxy-Certificate][Routes][2-sided Authentication]

### ISSUE THREAD

**Issue by sanadhis** [fanout/pushpin#47661]
Hi, does it possible (or supported) to connect to a target using proxy (or client) certificates?

For example I have an nginx server as an upstream server and it always verifies the client requests (clients' certificate). So when no certificate is given, the upstream server will never process the request.

**Comment by jkarneges** [comment]
Hi,

Unfortunately cert auth to the route target is not possible. As a workaround you could auth by shared key using a header, by setting the `header` param on the route.
