### ISSUE TITLE
Unexpected server response: 502

### ISSUE THREAD

**Issue by frey1esm** [fanout/pushpin#47662]
While going through the [Pushpin Crash Course on YouTube](https://www.youtube.com/watch?v=G9vVoN2tyeM), this command:

`wscat --connect ws://localhost:7999/testwebsocket.php`

Generates this error:

`error: Unexpected server response: 502`

This is a fresh server running Apache and it's definitely an Apache config issue. @jkarneges if you can share your Apache setup config that'd be awesome, since the video indicates you're also running Apache.

**Comment by jkarneges** [comment]
Hi,

Be sure to install mod_php (for comparison, this is `libapache2-mod-php` on Ubuntu) and enable the module if the installation process doesn't do this for you (e.g. `a2enmod php7.2`). Restarting Apache afterwards could be a good idea.

With a working Apache and PHP, check that `testwebsocket.php` responds as such:

```
$ curl -i -d 'OPEN'$'\r'$'\n' http://localhost/testwebsocket.php
HTTP/1.1 200 OK
Date: Wed, 02 Jan 2019 00:29:20 GMT
Server: Apache/2.4.29 (Ubuntu)
Content-Length: 6
Content-Type: application/websocket-events

OPEN
```

Note that the above request is made directly to Apache (in my case, port 80).

Another thing is to ensure you've set an appropriate route in Pushpin's `routes` file:

```
* localhost:80,over_http
```

Hopefully that's enough to get things working.

**Comment by frey1esm** [comment]
mod_php is already installed and `testwebsocket.php` is responding as expected. Routes file is as shown also. The issue is within the Apache configuration I believe.

**Comment by jkarneges** [comment]
If curl is getting a successful response from the script, then Apache is probably set up correctly.

Let's see if we can get more information about that 502 response from Pushpin.

Try enabling debugging on the route:

```
*,debug localhost:80,over_http
```

This tells Pushpin to include extra information in error responses.

Then make a fake WebSocket request to Pushpin using curl:

```sh
curl -i -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" -H "Sec-WebSocket-Version: 13" http://localhost:7999/testwebsocket.php
```

Using curl here since I don't think it's possible to see full error responses with wscat.

**Comment by jkarneges** [comment]
Hmm, are you setting `debug` on the route? It should have given you a better error message. For example, if I point the route to a port that has no server process listening and then make a request, I get an error like this:

```sh
$ curl -i -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" -H "Sec-WebSocket-Version: 13" http://localhost:7999/testwebsocket.php
HTTP/1.1 502 
Content-Length: 57

Unable to connect to any targets. Tried: localhost:12345
```

**Comment by frey1esm** [comment]
I am not getting the same output as you, but you can see my routes file.

```
$ cat /etc/pushpin/routes
*,debug localhost:80,over_http
```

And your erroneous command:

```
$ curl -i -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" -H "Sec-WebSocket-Version:3" http://localhost:7999/testwebsocket.php
HTTP/1.1 502 Bad Gateway
Content-Length: 32

Error while proxying to origin.
```

**Comment by jkarneges** [comment]
Hmm, if we do the same thing and get different error messages then I suspect you're on an older version. What version of Pushpin are you using?

Aside from upgrading, the next thing you can try is running Pushpin with verbose logs enabled and show me your m2adapter.log and pushpin-proxy.log files (in a paste/gist).

**Comment by frey1esm** [comment]
`pushpin 1.18.0`

**Comment by frey1esm** [comment]
@jkarneges  I updated to `pushpin 1.18.0` and no longed receive a 502. I'm on a different machine  but will close the issue. If you see something relevant in the log files please post here.

**Comment by jkarneges** [comment]
Thanks for the logs. Found the key line at pushpin-proxy.log:1241

```
[DEBUG] 2019-01-03 21:10:00.915 zhttp/zws client: IN pushpin-proxy_26966 { "from": "{764a0209-028d-4b09-b4f2-da5287ba8d0e}", "headers": [ [ "Date", "Fri, 04 Jan 2019 02:10:00 GMT" ], [ "Server", "Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/5.4.16" ], [ "X-Powered-By", "PHP/7.0.27" ], [ "Transfer-Encoding", "chunked" ], [ "Content-Type", "application/websocket-events" ] ], "id": "b404d0aa-83f6-483a-9aa8-901219f4beae", "code": 200, "seq": 1, "reason": "OK" } 7 "OPEN\x0d\n\n"
```

The server response ends with `\r\n\n` which is invalid. I should have asked you to pipe the first curl test through `hexdump -C`. :)

Will look at improving the error message from Pushpin in this case.

I suspect your PHP file on the first machine had an extra newline.

**Comment by OpenFalcons** [comment]
yes I too faced the exact issue of extra line.. now solved..

Thanks @jkarneges
