### ISSUE TITLE
does Pushpin support changing route config at running time?

### ISSUE THREAD

**Issue by nghia1986** [fanout/pushpin#47672]
I wonder if there anyway that I can change route config at running time?
We have several servers behind pushpin. In order to update servers, we would like to remove them out of route config one by one.
Kong has that kind of feature.  Does pushpin support that ?

**Comment by jkarneges** [comment]
Yes and no.

Pushpin watches the `routes` file and reloads it if anything changes, so you can indeed change the routes at runtime.

However, Pushpin does not support specifying a set of servers to be load balanced to, nor does it perform health checks (Pushpin is not a load balancer). If you want to run Pushpin in front of multiple backend servers and round-robin the requests to them, you'll need a load balancer between Pushpin and the backend servers.
