### ISSUE TITLE
Missing content when sending/receiving PING/PONG

### ISSUE THREAD

**Issue by bkahraman** [fanout/pushpin#47683]
As already confirmed by @jkarneges in the pushpin community chat (https://gitter.im/fanout/pushpin?at=5e5d3c16ff6f6d2e887e783e) it is not possible to send/receive PING or PONGs with application data. Pushpin (1.20.1) seems to drop it completely.

Small js script to reproduce by replacing the URL with the pushpin proxy URL:
```const ws = require("ws");
const url = "wss://echo.websocket.org";
const socket = new ws(url);

socket.on("open", () => {
    console.log("open")
    socket.ping("foo")
});

socket.on("pong", buffer => {
    console.log('Received PONG')
    console.log(buffer.toJSON())
});
```

In my case I have a PHP Apache Server which received the following:
```
@file_get_contents('php://input') => "PING\r\n"
```

**Comment by jkarneges** [comment]
Thanks for the report. This is fixed in the develop branch. Will make a new release (1.27.0) shortly.

**Comment by bkahraman** [comment]
@jkarneges thanks a lot for the quick solution. I can confirm that passing the application data now works in both directions.
