### ISSUE TITLE
unable to install pushpin via Dockerfile [dl.bintray.com is forbidden]

### ISSUE THREAD

**Issue by bharath-naik** [fanout/pushpin#47698]
while i was building an image using pushpin Docker file, At step no 5 it has to install the pushpin version which is mentioned in the Docker environment variables. but the error shows forbidden

`
deb https://dl.bintray.com/fanout/debian fanout-bionic main

Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.pVorZ8Swiv/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
gpg: key 379CE192D401AB61: public key "Bintray (by JFrog) <bintray@bintray.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Removing intermediate container db3a12471a42
 ---> 25bd94031d0e \
Step 4/14 : ENV PUSHPIN_VERSION 1.31.0-1~bionic1 \
 ---> Running in 6cda52c4b13f
Removing intermediate container 6cda52c4b13f
 ---> 458ddff4c749
Step 5/14 : RUN   apt-get update &&   apt-get install -y pushpin=$PUSHPIN_VERSION
 ---> Running in 4b636b31a4ec
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease 
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Err:5 https://dl.bintray.com/fanout/debian fanout-bionic InRelease
  403  Forbidden [IP: 52.41.30.229 443]
Reading package lists...
E: Failed to fetch https://dl.bintray.com/fanout/debian/dists/fanout-bionic/InRelease  403  Forbidden [IP: 52.41.30.229 443]
E: The repository 'https://dl.bintray.com/fanout/debian fanout-bionic InRelease' is not signed.
The command '/bin/sh -c apt-get update &&   apt-get install -y pushpin=$PUSHPIN_VERSION' returned a non-zero code: 100
`
can anyone tell, what should i do next.

**Comment by jkarneges** [comment]
Hi, the APT repo has moved. See the latest Dockerfile here: https://github.com/fanout/docker-pushpin
