### ISSUE TITLE
Ignored messages

### ISSUE THREAD

**Issue by davidkralprofinit** [fanout/pushpin#47693]
Hello,

my setup is: nginx->pushpin->Java backend

routes: * server_name:8080,over_http

I am using fanout/pushpin:1.28.0.

Everything works great untill i try to send more than 2 messages right after each other.

I can see first two messages in log, but the third is not there:

[INFO] 2020-11-20 09:40:04.112 [zurl] IN id=be851d21-ae4a-4c16-a286-855c3473dc6e, POST http://pushpin/api/websocket
[INFO] 2020-11-20 09:40:04.648 [zurl] OUT id=be851d21-ae4a-4c16-a286-855c3473dc6e code=200 177
[INFO] 2020-11-20 09:40:04.668 [handler] subscribe ws://pushpin/api/websocket channel=channelName1
[INFO] 2020-11-20 09:40:04.672 [zurl] IN id=706c9b58-fb4d-4d94-983e-fe94ed5fb9c0, POST http://pushpin/api/websocket
[INFO] 2020-11-20 09:40:05.052 [zurl] OUT id=706c9b58-fb4d-4d94-983e-fe94ed5fb9c0 code=200 177
[INFO] 2020-11-20 09:40:05.054 [handler] subscribe ws://pushpin/api/websocket channel=channelName2

If I use some kind of delays, all messages are deliviered.

Thanks

**Comment by jkarneges** [comment]
Hi,

You are saying if the client sends 3 messages, only 2 are being sent to the backend server?

**Comment by jkarneges** [comment]
One possibility is the messages are getting batched. The second request to the backend might contain two messages.

**Comment by davidkralprofinit** [comment]
Hello,

You are right, second and third message are batched. Is it possible to disable batching? A have not found any option.

Thank you very much

**Comment by jkarneges** [comment]
Yes, try the `one_event` route target parameter.

**Comment by davidkralprofinit** [comment]
Works great, thank you.

**Comment by jkarneges** [comment]
No problem. :) I'll close this issue then.
