### ISSUE TITLE
Bintray sunsetting

### ISSUE THREAD

**Issue by chrisbodhi** [fanout/pushpin#47695]
Howdy,

While investigating a failure in our build step that installs Pushpin, I found out that [Bintray is being sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/); our build failure is because we were attempting to build during [a scheduled brownout of the Bintray](https://status.bintray.com/incidents/4mzph0y8l6hk). I'm opening this issue to bring to your attention that we'll need a new hosting solution soon.

Thanks much.

**Comment by jkarneges** [comment]
Hi Chris,

Indeed, this is being looked into. Sorry about any download failures.

**Comment by chrisbodhi** [comment]
Hi @jkarneges,

We're looking into options that circumvent Bintray in our build step. We started by looking at the Docker image recommended in the docs, but that also depends on Bintray. Any progress on your end in moving toward a new hosting solution, or the timeline for doing so?

**Comment by jkarneges** [comment]
Yes, we should be up and running on JFrog Artifactory in the next day or so.

**Comment by jkarneges** [comment]
This is done. [Installation docs](https://pushpin.org/docs/install/) and [Dockerfile](https://github.com/fanout/docker-pushpin/blob/master/Dockerfile) have been updated.

**Comment by chrisbodhi** [comment]
Rad, thanks, @jkarneges!

**Comment by Bo98** [comment]
I should perhaps ask in the other repo, but is there a migration planned for Zurl?

(Also, the links here need updating: https://fanout.io/download/)

**Comment by jannic** [comment]
> I should perhaps ask in the other repo, but is there a migration planned for Zurl?

Zurl packages are available from JFrog Artifactory as well.  The installation docs at https://pushpin.org/docs/install/ cover the installation of both pushpin and its dependencies.

**Comment by Bo98** [comment]
I should have been specific: I was looking for the source tarball that was provided at https://dl.bintray.com/fanout/source/zurl-1.11.0.tar.bz2. It was migrated to GitHub releases here but doesn't seem to have been in the Zurl repo.

(I realise the Git repo itself is also available for that purpose though - it would just be nice to have a URL that can easily be swapped without updating checksums)

**Comment by jkarneges** [comment]
Hi @Bo98, that Zurl tarball is now available on GitHub as well: https://github.com/fanout/zurl/releases

**Comment by Bo98** [comment]
Thanks @jkarneges!
