### ISSUE TITLE
Brew installation of Pushpin not able to run in MacOS Big Sur

### ISSUE THREAD

**Issue by ericklind** [fanout/pushpin#47694]
I setup pushpin using brew on my Mac, but whenever I try to run it, I get the following in my terminal:
```
INFO] 2020-11-21 11:59:10.314 starting...
[INFO] 2020-11-21 11:59:10.315 using config: /usr/local/etc/pushpin/pushpin.conf
[INFO] 2020-11-21 11:59:10.315 starting condure
[INFO] 2020-11-21 11:59:10.316 starting zurl
[INFO] 2020-11-21 11:59:10.317 starting proxy
[INFO] 2020-11-21 11:59:10.318 starting handler
[INFO] 2020-11-21 11:59:10.321 started
[ERR] 2020-11-21 11:59:10.354 handler: Exited unexpectedly
[INFO] 2020-11-21 11:59:10.355 stopping condure
[INFO] 2020-11-21 11:59:10.355 stopping zurl
[INFO] 2020-11-21 11:59:10.355 stopping proxy
[INFO] 2020-11-21 11:59:10.381 stopped
```
Sometimes there is a flash of a modal asking to Allow something (I assume incoming port connections), but it disappears before I can click Allow. Any ideas why this is happening and how I might fix it?

 I'm running Big Sur, but since this is my first time trying to run pushpin I'm not sure if that's a contributing factor.

**Comment by jkarneges** [comment]
I don't think we've tested on Big Sur yet.

A couple of ideas:

* Try running `pushpin-handler` directly and see if it runs or crashes (passing no arguments should be fine). If it crashes, there may be more output this way.
* In case there's some issue with bottles, try `--build-from-source` when installing.

**Comment by ericklind** [comment]
I did a reinstall with brew using `--build-from-source`, but there was no difference.

I was able to get it to it to work with Docker, so I'll stick with that for no.

I'm interested in figuring out why it didn't work the normal way, so how do I run the handler directly?

**Comment by jkarneges** [comment]
After installing pushpin, the `pushpin-handler` program should be in your PATH and you can just run it.

**Comment by ericklind** [comment]
I got the following:

```
➜  server pushpin-handler
[INFO] 2020-11-22 17:06:58.533 starting...
[INFO] 2020-11-22 17:06:58.538 zhttp in stream: ipc:///usr/local/var/run/pushpin/pushpin-condure-out-stream
[INFO] 2020-11-22 17:06:58.538 zhttp out: ipc:///usr/local/var/run/pushpin/pushpin-condure-in
[INFO] 2020-11-22 17:06:58.538 inspect server: ipc:///usr/local/var/run/pushpin/pushpin-inspect
[INFO] 2020-11-22 17:06:58.538 accept server: ipc:///usr/local/var/run/pushpin/pushpin-accept
[ERR] 2020-11-22 17:06:58.538 unable to bind to tcp://127.0.0.1:5563

```
Are there any arguments that it needs?

**Comment by jkarneges** [comment]
It looks like binding to port 5563 is failing. You must have something else running on that port.

You can change the port to something else in /usr/local/etc/pushpin/pushpin.conf

**Comment by ericklind** [comment]
I was never able to discover what was running on 5563. I changed the port to 5564 and ran `pushpin-handler`, and it seems to be running. The only problem now is that when I try to connect using the node example, I get:

```
➜  server wscat --connect ws://localhost:7999/api/websocket
error: connect ECONNREFUSED 127.0.0.1:7999
```

Any idea why that is the case and how to get past it?

**Comment by jkarneges** [comment]
Probably because the rest of pushpin isn't running. Now that you've managed to get `pushpin-handler` to work on its own, you can terminate it and run `pushpin` normally.

**Comment by ericklind** [comment]
Thanks. Now `pushpin` works, but I'm getting:

```
➜  server wscat --connect ws://localhost:7999/api/websocket
error: Unexpected server response: 404
```
Thoughts?

**Comment by jkarneges** [comment]
What does your `routes` file look like?

**Comment by ericklind** [comment]
I run lots of react apps so I moved it to 3001. Is there 

`* localhost:3001`

The other ip addresses/ports in the .conf file are:

```
# plain HTTP port to listen on for client connections
http_port=7999

# bind PULL for receiving publish commands
push_in_spec=tcp://127.0.0.1:5560

# list of bind SUB for receiving published messages
push_in_sub_specs=tcp://127.0.0.1:5562

# addr/port to listen on for receiving publish commands via HTTP
push_in_http_addr=127.0.0.1
push_in_http_port=5561

# bind REP for responding to commands
command_spec=tcp://127.0.0.1:5564

```

**Comment by jkarneges** [comment]
If you're getting a 404, then it means the server on port 3001 is returning 404.

Side note: to have WebSocket events converted to HTTP, you'll want the route to be:

```
* localhost:3001,over_http
```

**Comment by ericklind** [comment]
Okay, one step closer! 

Now I'm getting:
`error: Unexpected server response: 502`

When I run post on using:
`curl -X POST localhost:7999/api/websocket`

I get `[not a websocket request]`, which is what it's supposed to do, and the logging works.

This is the ws-express example, so it is expecting a websocket.

Also, thanks for your help on this!

**Comment by jkarneges** [comment]
If the backend is a websocket server, then in that case don't use `over_http`.

If you are still getting 502, look at zurl.log to see what is being sent to the backend and what is coming back.

**Comment by ericklind** [comment]
Maybe I'm missing something. In the express sample code, all of the endpoints are `app.post`, but are expecting a websocket. Is that how it's supposed to work? Or should they be `app.ws` endpoints?

Here's what zurl has to say:
```
[DEBUG] 2020-11-23 17:35:50.907 recv-init: { "ignore-policies": true, "seq": 0, "ext": { "multi": true }, "connect-host": "localhost", "from": "pushpin-proxy_42633", "headers": [ [ "Sec-WebSocket-Version", "13" ], [ "Sec-WebSocket-Key", "xX/nvHMBMK9cIVKznHReMg==" ], [ "Upgrade", "websocket" ], [ "Host", "localhost:7999" ], [ "Grip-Sig", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDYxODUzNTAsImlzcyI6InB1c2hwaW4ifQ.62OyJ8YPrs_MlNNCleTAoZVCBDA4m7TlfLMZNSVua2A" ], [ "Grip-Feature", "status, session, link:next, filter:skip-self, filter:skip-users, filter:require-sub, filter:build-id, filter:var-subst" ], [ "Sec-WebSocket-Extensions", "grip" ] ], "connect-port": 3001, "uri": "ws://localhost:7999/api/websocket", "credits": 200000, "id": "57238b5b-4031-41e4-a04b-f816e83544f9" }
[INFO] 2020-11-23 17:35:50.907 IN id=57238b5b-4031-41e4-a04b-f816e83544f9, ws://localhost:7999/api/websocket
[DEBUG] 2020-11-23 17:35:50.907 resolving: [localhost]
[DEBUG] 2020-11-23 17:35:50.908 ws: trying 127.0.0.1
[DEBUG] 2020-11-23 17:35:50.908 ws: connecting to 127.0.0.1:3001
[DEBUG] 2020-11-23 17:35:50.909 ws: sock_error: 0
[INFO] 2020-11-23 17:35:50.909 OUT ERR id=57238b5b-4031-41e4-a04b-f816e83544f9 condition=remote-connection-failed
[DEBUG] 2020-11-23 17:35:50.909 send: { "seq": 0, "condition": "remote-connection-failed", "from": "{3ab44e28-b65d-458a-9505-0f3071bf45a1}", "type": "error", "id": "57238b5b-4031-41e4-a04b-f816e83544f9" }
```

**Comment by jkarneges** [comment]
Which example are you using? The ones we've made are usually set up to use WebSocket-over-HTTP, where the backend receives POSTs instead of actual websocket connections. So, the use of `app.post` on the backend would be correct, and you'd set `over_http` on the Pushpin route.

**Comment by ericklind** [comment]
I'm using the [express-ws](https://github.com/fanout/js-serve-grip/blob/master/examples/express-ws/server.js) one in the examples folder. It has `app.post` endpoints.

If that is not how it's supposed to work, can you send me to a working example?

**Comment by jkarneges** [comment]
It turned out there were some issues with that example which are now fixed. Let me know if it still doesn't work for you.

**Comment by ericklind** [comment]
I updated the packages, but I'm still getting the exact same behavior when I run `wscat --connect ws://localhost:7999/api/websocket`

Here's the zurl.log:

```
[DEBUG] 2020-11-24 20:37:43.725 recv-init: { "seq": 0, "ext": { "multi": true }, "connect-host": "localhost", "connect-port": 3001, "from": "pushpin-proxy_93209", "uri": "ws://localhost:7999/api/websocket", "credits": 200000, "headers": [ [ "Sec-WebSocket-Version", "13" ], [ "Sec-WebSocket-Key", "bqdIEwPAaS5+DNpN6rfEMQ==" ], [ "Upgrade", "websocket" ], [ "Host", "localhost:7999" ], [ "Grip-Sig", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDYyODI2NjMsImlzcyI6InB1c2hwaW4ifQ.I27bFW0jJOKJPa6uF3ypAnquS3jPEll_a72FPpxx6bM" ], [ "Grip-Feature", "status, session, link:next, filter:skip-self, filter:skip-users, filter:require-sub, filter:build-id, filter:var-subst" ], [ "Sec-WebSocket-Extensions", "grip" ] ], "ignore-policies": true, "id": "3f5619b1-d79f-4bb0-b172-9ea75bd24523" }
[INFO] 2020-11-24 20:37:43.725 IN id=3f5619b1-d79f-4bb0-b172-9ea75bd24523, ws://localhost:7999/api/websocket
[DEBUG] 2020-11-24 20:37:43.726 resolving: [localhost]
[DEBUG] 2020-11-24 20:37:43.726 ws: trying 127.0.0.1
[DEBUG] 2020-11-24 20:37:43.726 ws: connecting to 127.0.0.1:3001
[DEBUG] 2020-11-24 20:37:43.726 ws: sock_error: 0
[INFO] 2020-11-24 20:37:43.726 OUT ERR id=3f5619b1-d79f-4bb0-b172-9ea75bd24523 condition=remote-connection-failed
[DEBUG] 2020-11-24 20:37:43.726 send: { "seq": 0, "type": "error", "from": "{dd875790-271e-4d46-8bf9-cb7e58b41099}", "id": "3f5619b1-d79f-4bb0-b172-9ea75bd24523", "condition": "remote-connection-failed" }
```

**Comment by jkarneges** [comment]
Be sure to use `over_http` in the pushpin route. The example expects to receive regular HTTP requests.

Also make sure the example is actually listening on port 3001.

**Comment by ericklind** [comment]
That was it. I forgot that I had removed the `over_http`;

Thanks for your help!

**Comment by jkarneges** [comment]
Glad it's finally working!

**Comment by ericklind** [comment]
I am finding the express server times out/disconnects after a while. Is there a better way to set this up so it reconnects or doesn't disconnect?

```
level: 'error',
  service: 'spark-analytics',
  timestamp: '2020-11-24 21:46:33',
  message: 'Client disconnected unexpectedly.',
  stack: 'Error: Client disconnected unexpectedly.\n' +
    '    at WebSocketContext.recvRaw (/Users/erick/Documents/spark-analytics/server/node_modules/@fanoutio/grip/src/data/websocket/WebSocketContext.ts:106:19)\n' +
    '    at WebSocketContext.recv (/Users/erick/Documents/spark-analytics/server/node_modules/@fanoutio/grip/src/data/websocket/WebSocketContext.ts:111:29)\n' +
    '    at /Users/erick/Documents/spark-analytics/server/server/p_server.ts:49:33\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /Users/erick/Documents/spark-analytics/server/server/p_server.ts:8:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (/Users/erick/Documents/spark-analytics/server/server/p_server.ts:4:12)\n' +
    '    at /Users/erick/Documents/spark-analytics/server/server/p_server.ts:21:47\n' +
    '    at Layer.handle [as handle_request] (/Users/erick/Documents/spark-analytics/server/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/erick/Documents/spark-analytics/server/node_modules/express/lib/router/route.js:137:13)'
}
```

**Comment by jkarneges** [comment]
The library generates this exception if a client disconnects uncleanly. If you don't care about the difference between a clean close and an abrupt disconnect (most apps don't), you can just wrap in a try/catch and ignore.

**Comment by ericklind** [comment]
Cool. Thanks again for all your help!
